### ISSUE TITLE
"makefile" What is it exactly? CMake clobbers it. Why is it here?

### ISSUE THREAD

**Issue by mick-p1982** [libglui/glui#108]
https://raw.githubusercontent.com/libglui/glui/master/makefile

Why is this file maintained? I've renamed it to makefile.zip because this is standard file name that isn't compatible with CMake. It's also a problem that it's lowercase on Windows, because it gets erased from the working copy when overwritten with the more standard "Makefile" name. 

Sure it can bypass CMake? But is it needed to support any platforms the CMake script cannot (Apple?) because it has some Commits in the history, but is generally a nuisance.

**Comment by nigels-com** [comment]
GNU Make is an old-school build system still widely used for Linux and other UNIX software.
For more details: https://www.gnu.org/software/make/

Recommended practice for cmake is to build out of source, or in a subdirectory named **build**.

Such as:
```
mkdir build
cd build
cmake ..
make
```

There does tend to be some confusion that there can be a project maintained Makefile along with a cmake-generated Makefile.  For small projects such as GLUI GNU make tends to be adequate, but admittedly exotic for the unintiated.

With the proliferation of GNU make alternatives nowadays there does tend to be a demand of projects to support this, that and everything.  I tend to treat the GNU make build as the one that must-not-break, ever.  It has the one merit of being rock solid stable and reliable, and available nearly everywhere.
