### ISSUE TITLE
type clashes on Mac OS X 

### ISSUE THREAD

**Issue by josch** [libglui/glui#19]
https://sourceforge.net/p/glui/bugs/25/
# initial report

It seems that MacTypes.h:646 tries to redefine a type that has already been defined if <CoreFoundation CFBundle.h=""> is included.

i don't know if a precompiler command like #if !defined(MACTYPES) could fix this. So the types won't be redefined again.

The error message:
error: multiple types in one declaration
error: declaration does not declare anything

The line causing the error:

```
    typedef UInt8 Byte;
```
# reply 1

Sorry for my early post. it seems like
glui.h line 75 and following define the
byte type and is the reason for the clash.

```
#ifndef Byte
#define Byte unsigned char
#endif
```

a simple #undef Byte directly after
`#include <GLUI glui.h="">` fixed this.

**Comment by nigels-com** [comment]
Surely GLUI ought to embrace uint_8, rather than Byte?

**Comment by josch** [comment]
Since `char` is defined to be exactly 8 bits on all platforms, it should not matter whether `unsigned char` or `uint8_t` is used. Though I don't think this bug is relevant anymore because the only mentioning of `Byte` in the current code is from a commented out section in `glui_internal.h`. I do not have access to an Apple OS so I cannot test whether glui compiles on it in its current form. I'll close this bug once somebody can confirm that it compiles there.

**Comment by nigels-com** [comment]
I have an old Mac that I boot up on occasion.  I'll give this a spin next time I'm in Mac mode.
