### ISSUE TITLE
GLUI 2.36 

### ISSUE THREAD

**Issue by josch** [libglui/glui#24]
https://sourceforge.net/p/glui/bugs/32/

Hi,

I send you a patch for the examples of glui.
I hope that you will apply it.
thanks.

    Index: src/example/example1.cpp
    ===================================================================
    --- src/example/example1.cpp
    +++ src/example/example1.cpp    2010-03-21 18:03:22.000000000 +0100
    @@ -136,7 +136,7 @@
     
       glutMainLoop();
     
    -  return EXIT_SUCCESS;
    +  return 0;
     }
     
     
    Index: src/example/example2.cpp
    ===================================================================
    --- src/example/example2.cpp
    +++ src/example/example2.cpp    2010-03-21 18:05:05.000000000 +0100
    @@ -253,5 +253,5 @@
     
       glutMainLoop();
     
    -  return EXIT_SUCCESS;
    +  return 0;
     }
    Index: src/example/example3.cpp
    ===================================================================
    --- src/example/example3.cpp
    +++ src/example/example3.cpp    2010-03-21 18:07:04.000000000 +0100
    @@ -437,6 +437,6 @@
       /**** Regular GLUT main loop ****/  
       glutMainLoop();
     
    -  return EXIT_SUCCESS;
    +  return 0;
     }
     
    Index: src/example/example4.cpp
    ===================================================================
    --- src/example/example4.cpp
    +++ src/example/example4.cpp    2010-03-21 18:08:13.000000000 +0100
    @@ -351,6 +351,6 @@
       
       glutMainLoop();
     
    -  return EXIT_SUCCESS;
    +  return 0;
     }
     
    Index: src/example/example5.cpp
    ===================================================================
    --- src/example/example5.cpp
    +++ src/example/example5.cpp    2010-03-21 18:09:45.000000000 +0100
    @@ -496,6 +496,6 @@
       
       glutMainLoop();
     
    -  return EXIT_SUCCESS;
    +  return 0;
     }

**Comment by nigels-com** [comment]
In my opinion, EXIT_SUCCESS is the correct code.  Perhaps an #include is missing.
The platform/compiler isn't mentioned, unfortunately.

**Comment by josch** [comment]
Since it compiles fine on GNU/Linux and Windows 7 and I also prefer `EXIT_SUCESS` I'll just close this report. The original report also did not mention whether an include was missing or not or whether there was a compilation problem in the first place. There is the argument that `EXIT_SUCESS` is more portable but personally I just find it more readable.
