### ISSUE TITLE
Show/hide subwindow on Cygwin/X

### ISSUE THREAD

**Issue by mick-p1982** [libglui/glui#81]
Me:
> > their WGL context, meaning that OpenGL textures are probably lost
> and the context is inoperable, which is a whole other class of
> problems.

Jon:
> Hmmm, yes.  The native windows are created/destroyed when the X windows 
are mapped/unmapped, for reasons lost in the mists of time.

I've spent the last week and a half or so working on a POSIX port using Cygwin. As much as I'd like to discount the entire Linux world for its sloppiness and time-consuming, fussy software; it seems like a fixture. http://www.swordofmoonlight.net/bbs2/index.php?action=dlattach;topic=234.0;attach=509;image

I don't see any reason to discount Cygwin and not discount anyone else's system. The problem is Cygwin's built-in X server just can't use the XUnmapWindow and XMapWindow APIs until their team fixes their half-assed code. Jon doesn't seem too concerned that their X server flat doesn't work. I am going to add this to their issue-tracker, but the list of issues there are few and old. Luckily its the same tracker I registered with the other day while having issues with a broken version of ld or gcc. 

I can't implement a short term fix for this if I cannot change the GLUT window ID of the subwindow. I don't want to recreate the window every time it is shown and hidden, and I'd prefer if GLUI could manage this independently, although I can understand why that would be objectionable, but it already generates GLUT window IDs when the subwindow is created.... another possibility is setting the window's size to 0,0. (GLUI offers no way for users to control this--that will have to change.)

P.S. While working with GLUI I noticed two things about hide/show. 1) when hidden the windows still draw themselves. Pointlessly. 2) The space occupied by the hidden window is not collapsed. It remains as a hole. Fortunately for me I decided that A) I only need one subwindow for now; and B) It was a better user experience if the window obscured the viewport than if it made it shrink when toggled.

**Comment by mick-p1982** [comment]
Note: this is really a problem in freeglut, but I don't expect its group to raise a finger either. Their demos are all broken. Generally speaking when a windows comes out of iconized state it needs to be refreshed, but when a window comes out of hidden state, its GLX context is no more (destroyed when hidden) and so the window itself must be recreated.

**Comment by nigels-com** [comment]
Doesn't seem like a GLUI problem.  Closing.
