### ISSUE TITLE
GLUI_FileBrowser callback not triggered

### ISSUE THREAD

**Issue by agarrett** [libglui/glui#83]
The GLUI_FileBrowser callback mechanism works for me with glui-2.36, but not with glui-2.37. 

Simple test: double clicking a file, on file browser list, gets a callback call in 2.36, but not in 2.37. Test on Mac OSX (10.12.6).

Is this a known issue (maybe with a patch)!? 

I used cmake / make, to build a static archive from 2.37, and from my git cloned development code, but no luck with either, only 2.36 built archive works!

**Comment by nigels-com** [comment]
I think there is a problem here with storing the timestamp of the first click.

Try the fix in pull #84 - confirm it solves your problem, thanks.

**Comment by agarrett** [comment]
My testing got muddled. Using an IDE build, and a completely separate Makefile, tripped me up.  

2.36 and 2.37 both work correctly on OS/X.

But development (clone of glui.git) did not. I applied your patch, and dev works too. Thx.

Have not yet upgraded, on Ubuntu and Debian, but 2.36 Linux versions also good.

**Comment by nigels-com** [comment]
Thanks for checking, the fix has been merged.
